### ISSUE TITLE
Reference donejs #609: Make development.html use hashchange routing ~8

### ISSUE THREAD

**Issue by ilyavf** [donejs/generator-donejs#113]
Just a reference issue to [DoneJS #609](https://github.com/donejs/donejs/issues/609)

**Comment by justinbmeyer** [comment]
Fixed here: https://github.com/donejs/generator-donejs/pull/137

**Comment by phillipskevin** [comment]
Closed in 1.0 by https://github.com/donejs/generator-donejs/pull/184.
