### ISSUE TITLE
Plugin Generator Root Folder Steal Test Path with System.directories.lib

### ISSUE THREAD

**Issue by jandjorgensen** [donejs/generator-donejs#116]
For the plugin generator, the path to steal on the test page isn't being generated correctly, specifically for the root folder (`.`) when `System.directories.lib` is set to `"."`

For the following SystemJS Config:
```
"system": {
    "directories": {
        "lib": "."
    }
}
```

And the generator config:
```
? Project name can-util
? Project main folder .
? Description Common utilities for CanJS projects
? Project homepage url http://canjs.com
? GitHub username or organization canjs
? Author's Name Bitovi
? Author's Email contact@bitovi.com
? Author's Homepage http://bitovi.com
? Application keywords Can,JS
? NPM version used 3
Writing package.json v0.9.2
```

**Comment by justinbmeyer** [comment]
Also the path to `.jshint` is wrong: `"jshint": "jshint src/. --config",`

**Comment by justinbmeyer** [comment]
Though I'm not sure what that should be to not include node_modules.

**Comment by justinbmeyer** [comment]
path is also wrong for src/test/test.html
