### ISSUE TITLE
Update viewModel syntax

### ISSUE THREAD

**Issue by matthewp** [donejs/generator-donejs#12]
When 2.3.0-pre.3 is released the generator should be updated to the new syntax. Instead of:

```handlebars
<can-import from="appstate" [.]="{value}" />
```

It becomes:

```handlebars
<can-import from="appstate" as="viewModel" />
```

**Comment by justinbmeyer** [comment]
could as="{viewModel}" work?

**Comment by justinbmeyer** [comment]
this doesn't work for me ... not sure what else I need to update.

**Comment by matthewp** [comment]
Should just be as="viewModel", ping me today if it's still not working for you.

**Comment by daffl** [comment]
This has been fixed a while ago.
