### ISSUE TITLE
supermodel: model name should be required

### ISSUE THREAD

**Issue by marshallswain** [donejs/generator-donejs#126]
If you don't provide a model name, you get this:

![screen shot 2016-04-29 at 12 40 14 pm](https://cloud.githubusercontent.com/assets/128857/14926077/a1d6f1de-0e07-11e6-9074-7ba051804363.jpg)

**Comment by phillipskevin** [comment]
Closed in 1.0 by https://github.com/donejs/generator-donejs/pull/184.
