### ISSUE TITLE
Cache npm modules

### ISSUE THREAD

**Issue by marshallswain** [donejs/generator-donejs#128]
It would be really nice to have a version of the generator that would work offline.  I originally thought that local-npm would work for this, but it's not as transparent of an experience as I thought it would be. (You have to change the npm registry using `npm set registry http://127.0.0.1:5080`.)  https://addyosmani.com/blog/using-npm-offline/ 

@justinbmeyer It would probably be better to do our own internal caching as you suggested.

**Comment by marshallswain** [comment]
https://addyosmani.com/blog/using-npm-offline/

**Comment by pYr0x** [comment]
for donejs-vagrant (https://github.com/donejs/donejs-vagrant) i used npm_lazy. it will not copy the whole npm database.
you have also to change the npm registry, but with `npmrc` you can switch very fast. 
https://github.com/donejs/donejs-vagrant/blob/master/config/npm_lazy/init.sh#L11

the good on npm_lazy is, that it will automaticly update the package if there is a new version available

**Comment by marshallswain** [comment]
Thanks @pYr0x. npm_lazy is definitely working better than local-npm.  I noticed that the only way for it to use the cache is if it can't reach the npm server.  Having a way to force generator-donejs to use the cache would be really nice for slow internet connections.

**Comment by marshallswain** [comment]
Adding support for [yarn](https://yarnpkg.com/) would solve the speed issue, but it might be nice to come up with a solution that works without needing to install yarn.  Not sure if it's worth it, really.  I would kinda rather just use yarn's API.

**Comment by justinbmeyer** [comment]
Closing for https://github.com/donejs/generator-donejs/issues/145
