### ISSUE TITLE
Tests are failing for NodeJS v6

### ISSUE THREAD

**Issue by ilyavf** [donejs/generator-donejs#138]
Last success test [using node v5.10.1 (npm v3.8.3)](https://travis-ci.org/donejs/generator-donejs/jobs/124217981)

Latest failing test [using node v6.3.0 (npm v3.10.3)](https://travis-ci.org/donejs/generator-donejs/jobs/142845689#L673)

**Comment by justinbmeyer** [comment]
Related: https://github.com/donejs/donejs/issues/705

**Comment by phillipskevin** [comment]
Seems like this is working fine again after https://travis-ci.org/donejs/generator-donejs/jobs/169654313. Possibly fixed by https://github.com/donejs/generator-donejs/pull/150. @ilyavf @justinbmeyer any issue with closing this?

**Comment by phillipskevin** [comment]
https://github.com/donejs/generator-donejs/pull/150 was made against a `major` branch. Maybe this needs to be applied to `master`. @Sinjhin can you take a look?

**Comment by matthewp** [comment]
We really only care about major right now.
