### ISSUE TITLE
Add instructions for building the documentation to the readme

### ISSUE THREAD

**Issue by chasenlehara** [donejs/generator-donejs#139]
It’d be helpful to have instructions for building the docs in the generated readme.

I believe this is the file that needs to be modified: https://github.com/donejs/generator-donejs/blob/master/app/templates/readme.md

**Comment by matthewp** [comment]
That is correct!

**Comment by matthewp** [comment]
I'm moving this to donejs-documentjs since that is now how the documentation is added.

**Comment by matthewp** [comment]
Issue moved to [donejs/donejs-documentjs #3](https://github.com/donejs/donejs-documentjs/issues/3) via [**ZenHub**](https://www.zenhub.com/)
