### ISSUE TITLE
Component generator allows invalid names  ~2

### ISSUE THREAD

**Issue by matthewp** [donejs/generator-donejs#143]
Taken from https://github.com/donejs/donejs/issues/699 by @tomgreever  

---

When you do `donejs add component` the wizard allows you to input component names with only one word, like `cart` or `header` even though these names aren't allowed. All component tags have to be two words with a dash so that they don't conflict with existing HTML tags. The wizard should error if the user tries to input a single word, and message them to use at least two words separated by a dash.

**Comment by justinbmeyer** [comment]
Or maybe it just adds the package name in front.
