### ISSUE TITLE
Projects and components name ending in number ~5

### ISSUE THREAD

**Issue by MarcGodard** [donejs/generator-donejs#144]
I noticed that there seems to be issues when generating a component or project name ending with a number.

**Comment by MarcGodard** [comment]
Just a little more information:

if you create a project called 'Something9' it splits up the word with a hyphen 'Something-9' but isn't consistent throughout. At least on components it isn't.

**Comment by phillipskevin** [comment]
@MarcGodard Is this still an issue? If it is, can you explain what inconsistencies you're seeing?

Trying this on donejs 0.9, I see the directory created as `Something9`, but everywhere in the code it is written as `something-9`, which is the name in the package.json.

**Comment by phillipskevin** [comment]
Going to close this. Please re-open if anyone can reproduce this.
