### ISSUE TITLE
yarn support

### ISSUE THREAD

**Issue by marshallswain** [donejs/generator-donejs#147]
We could build support for [yarn](https://yarnpkg.com/) into our generator.  That way we could take advantage of the cache system and other perks.

**Comment by marshallswain** [comment]
https://github.com/donejs/generator-donejs/issues/145

**Comment by frank-dspeed** [comment]
Started Preparing sub Packages (dependencys) for usage with yarn they need updates in the package json because else yarn install will fail on most systems

**Comment by justinbmeyer** [comment]
Closing for https://github.com/donejs/generator-donejs/issues/145
