### ISSUE TITLE
Project name should validate against npm guidelines (eg. no caps, url-friendly)

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/generator-donejs#149]
> Originally: https://github.com/donejs/donejs/issues/415

I just created a project and gave it an invalid name:

```
donejs init
$ Project name: My Project
...
```

This resulted in invalid paths used in `index.stache`:

```html
<can-import from="My Project/styles.less!">
<can-import from="My Project/app" export-as="viewModel" />
```

Npm has pretty specific guidelines on naming a project - `donejs init` should provide some sort of validation or at least instruction on this: https://docs.npmjs.com/files/package.json

**Comment by phillipskevin** [comment]
@justinbmeyer are you sure you have the latest version? This should have been [fixed here](https://github.com/donejs/generator-donejs/commit/0cada27fb494ab1fe817b48216d4bc0521de66cc).


Also, trying it out I don't see the issue you see:
```
donejs add app
? Project name My Project
...
    <can-import from="my-project/styles.less!" />
    <can-import from="my-project/app" export-as="viewModel" />
```

**Comment by Sinjhin** [comment]
Just looked through the code and determined this is closed.
