### ISSUE TITLE
Default keywords for new plugin

### ISSUE THREAD

**Issue by nriesco** [donejs/generator-donejs#157]
It would be great to add some default keywords when creating a plugin. Right now if no keyword is defined package.json will be filled with `"keywords": [],` what makes donejs plugins hard to find. Adding something like `donejs-plugin` would be good enough.

**Comment by chasenlehara** [comment]
Great suggestion @nriesco & @phillipskevin!

[Kind of related.](https://github.com/donejs/donejs/issues/682) In addition to a curated list, we could link to an npm search for people to explore on their own.

**Comment by andrejewski** [comment]
Added in #233
