### ISSUE TITLE
app generator doesn't produce the correct production script

### ISSUE THREAD

**Issue by matthewp** [donejs/generator-donejs#173]
It should use the new Steal feature that puts steal.production.js into the dist folder.

**Comment by pYr0x** [comment]
i think this was done by kevin
https://github.com/donejs/generator-donejs/blob/major/app/templates/production.html#L7

**Comment by matthewp** [comment]
@pYr0x I'm referring to the index.stache. That's what is rendered by done-ssr.

**Comment by matthewp** [comment]
https://github.com/donejs/generator-donejs/blob/major/app/templates/src/index.stache#L13  

main is not needed and should use `dist/steal.production.js`.

**Comment by phillipskevin** [comment]
yeah, when I fixed the production.html, the index.stache wasn't working for me in production mode, so it needs to be changed now that it's working.

**Comment by matthewp** [comment]
Fixed by #175
