### ISSUE TITLE
Minimize plugin dist files produced for npm

### ISSUE THREAD

**Issue by chasenlehara** [donejs/generator-donejs#203]
The files in the `dist` folder aren’t minified before being published to npm.

**Comment by justinbmeyer** [comment]
@chasenlehara generally speaking, we don't publish minified versions of things.  Most people know how to use a minifier.

**Comment by chasenlehara** [comment]
@justinbmeyer I think I understand not minifying the AMD or CJS versions, but what about creating a minified global file? Or if not that, maybe provide easy docs for how to create one?

**Comment by andrejewski** [comment]
Closed by #255
