### ISSUE TITLE
Don’t change new app names that include numbers

### ISSUE THREAD

**Issue by chasenlehara** [donejs/generator-donejs#225]
When a new app has a name with a number in it, DoneJS modifies the name it puts in the `package.json` and README.

__Steps to reproduce:__

1. `donejs add app hot5`
2. Accept the defaults when prompted

__Expected results:__

- `name` in `package.json` would be `hot5`
- `repository.url` in `package.json` would include `hot5`
- README would have `hot5` in it

__Actual results:__

- `name` in `package.json` is `hot-5`
- `repository.url` in `package.json` includes `hot-5`
- README has `hot-5` throughout

__Environment:__

| Software                             | Version
| -------------------------- | -------
| donejs -V                            | 1.0.0
| node -v                               | 6.9.1
| npm -v                                | 4.2.0

**Comment by chasenlehara** [comment]
Bumped this in priority because the app doesn’t fully work out of the box; it’s not just an inconvenience, it’s actually broken.

**Comment by matthewp** [comment]
Will take this since I'm working on some generator stuff now.

**Comment by matthewp** [comment]
@chasenlehara What issues were you experiencing with the app not working? I am seeing what you describe with `hot-5`, but do not see any issues with the app running.

**Comment by chasenlehara** [comment]
You’re right, there aren’t issues with just `hot5`. I had created an app that was more like `hot5.com` and _that_ does create more issues (`NODE_ENV=production donejs start` spews errors). I can create a separate issue for that if you’d like.

**Comment by matthewp** [comment]
Could be a steal build issue if it's just a production problem.
