### ISSUE TITLE
Publishes by Travis

### ISSUE THREAD

**Issue by andrejewski** [donejs/generator-donejs#230]
Travis CI offers an NPM publish hook, as described in [their documentation](https://docs.travis-ci.com/user/deployment/npm/). 

Essentially, the flow is:
- Create a git tag using `npm version {major|minor|patch}`
- Push to Github `git push --tags`
- Travis will run like normal
- If successful, Travis publishes to NPM

To do this, we need to add deployment options to `.travis.yml`, see [an example config](https://github.com/andrejewski/rove/blob/master/.travis.yml). The person who creates the secure `api_key` is who Travis will publish as.

The benefits to this approach:
- All version bumps must pass CI, guaranteed.
- We do full testing because it is CI, so Browserstack/Saucelabs tests run.
- We don't have to add more collaborators through NPM's interface as all publishing will be done through a single user (probably good to make a single Bitovi publish account on NPM).

We should add this.

**Comment by chasenlehara** [comment]
What’s the process if the build fails in Travis and requires a code change? Make changes and push a new tag/version, or…?

**Comment by andrejewski** [comment]
I was not able to find anything specific to Travis releases, but since Travis uses webhooks we can use Git for moving the release tag to the fixed commit. [Here is a good example of that.](http://stackoverflow.com/questions/8044583/how-can-i-move-a-tag-on-a-git-branch-to-a-different-commit)

**Comment by andrejewski** [comment]
Closing as this has been implemented in many projects (multiple exclamation points):
  - grunt-testee
  - can-dom-event-radiochange
  - can-dom-event-enter
  - can-dom-events
  - can-dom-mutate
