### ISSUE TITLE
License in package.json

### ISSUE THREAD

**Issue by andrejewski** [donejs/generator-donejs#231]
See [`license` field in `package.json`](https://docs.npmjs.com/files/package.json#license). This should be default like the LICENSE file.

Package.json written here: https://github.com/donejs/generator-donejs/blob/master/plugin/index.js#L105

**Comment by leoj3n** [comment]
Lookin at this PR might help you with making the prompt:

https://github.com/donejs/generator-donejs/pull/136/files

**Comment by andrejewski** [comment]
Added by #232
