### ISSUE TITLE
Ignore trailing slashes when running donejs add component

### ISSUE THREAD

**Issue by chasenlehara** [donejs/generator-donejs#248]
__Steps to reproduce:__

Within a DoneJS app, run:

`donejs add component components/past-year/ past-year`

__Expected results:__

A warning or the following output from the CLI:

```shell
   create src/components/past-year/past-year.html
   create src/components/past-year/past-year.js
   create src/components/past-year/past-year.md
   create src/components/past-year/past-year.less
   create src/components/past-year/past-year.stache
   create src/components/past-year/past-year-test.js
   create src/components/past-year/test.html
```

__Actual results:__

The following files were created:

```shell
   create src/components/past-year/.html
   create src/components/past-year/.js
   create src/components/past-year/.md
   create src/components/past-year/.less
   create src/components/past-year/.stache
   create src/components/past-year/-test.js
   create src/components/past-year/test.html
```

__Environment:__

| Software                             | Version
| -------------------------- | -------
| donejs -V                            | 1.0.0
| generator-donejs version  | 1.0.5
| node -v                               | 7.9.0
| npm -v                                | 4.2.0
| Operating system              | macOS 10.12

**Comment by chasenlehara** [comment]
Reopening this issue because @mjstahl ran into it with [generator-donejs@1.0.7](https://github.com/donejs/generator-donejs/releases/tag/v1.0.7)

**Comment by cherifGsoul** [comment]
@chasenlehara I checked the test, it passes, I'm still investigating why it doesn’t work!
