### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by chasenlehara** [donejs/generator-donejs#253]
I’d like a new version of this package released before I [Update the Quick Start presentation for DoneJS 1.0](https://github.com/donejs/developer-relations/issues/47).

I’m not sure if the next version should be a patch or minor release. Here’s the diff: https://github.com/donejs/generator-donejs/compare/v1.0.5...master

**Comment by matthewp** [comment]
Why do you want a new release? Is there a feature here you need?

**Comment by matthewp** [comment]
I don't mind releasing a new version of course, just curious.

**Comment by chasenlehara** [comment]
I specifically want https://github.com/donejs/generator-donejs/pull/247 released because it affects the CLI output. The changes in https://github.com/donejs/generator-donejs/pull/234 and https://github.com/donejs/generator-donejs/pull/239 are also nice improvements, so I’m not sure if this should be a patch or minor release. Comments appreciated. 😊

**Comment by matthewp** [comment]
I think patch is fine here, removing a logging message isn't a "feature" so I don't think minor is necessary.

**Comment by andrejewski** [comment]
v1.0.6 was released with these changes. Closing
