### ISSUE TITLE
NPM 6 warns of packages with critical and high vulnerabilities when creating a new app

### ISSUE THREAD

**Issue by mjstahl** [donejs/generator-donejs#284]
__How often can you reproduce it?__ 

- [X] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
After creating a new DoneJS app, the User has to run `npm audit fix` to update packages that have vulnerabilities.

__Steps to reproduce:__

1. `donejs add app`
2. Fill out the requested information

<img width="884" alt="screen shot 2018-06-25 at 06 07 49" src="https://user-images.githubusercontent.com/212726/41847593-7ac5c716-7848-11e8-8a92-cf46bd5b8201.png">

__Expected results:__
Not to have a brand new application with critical vulnerabilities.

__Actual results:__
A brand new application with 15 noted vulnerabilities (2 high, 1 critical). 

Most likely of no consequence, but it just looks bad.

__Environment:__

| Software                             | Version
| -------------------------- | -------
| donejs -V                            | 2.1.0
| npm ls generator-donejs   | 2.1.0
| node -v                               | 10.5.0
| npm -v                                | 6.1.0
| Operating system              | macOS 10.13.5

**Comment by mjstahl** [comment]
* (low) generator-donejs > yeoman-generator > mem-fs-editor > deep-extend  (patched in >=0.5.1)
* (low) generator-donejs > lodash (patched in >=4.17.5)
* (HIGH) funcunit > jquery (patched in >=3.0.0)

The other 12 vulnerabilities can be resolved by 

`npm install --save-dev testee@0.8.0`

**Comment by frank-dspeed** [comment]
https://github.com/bitovi/testee/issues/177

**Comment by frank-dspeed** [comment]
https://github.com/donejs/donejs/issues/1110#issuecomment-416041064

**Comment by matthewp** [comment]
This is fixed in major, no vulnerabilities:

<img width="710" alt="screen shot 2018-11-02 at 8 39 25 am" src="https://user-images.githubusercontent.com/361671/47915969-eb4f0180-de7a-11e8-81fc-d8d73cdb5c25.png">
