### ISSUE TITLE
Remove the use of "short name" from the donejs generators

### ISSUE THREAD

**Issue by mjstahl** [donejs/generator-donejs#3]
We should remove the need for the user to be concerned about the application's short name.  

Therefore we should remove it from the `init` command, and its use in the `generate component` command.

I know the `generate component` command uses this for creating the tag names, here is how that should change:

`donejs generate component home.component` and `donejs generate component home` should take an additional argument of `<tag name>`.  

So in the specific example of the guide `donejs generate component home.component` would warn the user that the component tag does not have a `-` in it, and the go ahead and generate the component with a tag name of `home`.

Therefore we should update the guide to use the following command instead:

`donejs generate component home.component pmo-home`

`donejs generate component order/list.component` would generate a component located at `src/order/list.component` and the tag of the component would be `order-list`.

**Comment by daffl** [comment]
Done.
