### ISSUE TITLE
travis configuration not working in plugin

### ISSUE THREAD

**Issue by janat08** [donejs/generator-donejs#309]
generating plugin will have bad trasvis file, has error with trying to start xvfb, and https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node:

language: node_js
node_js:
  - "10"
services:
  - xvfb

**Comment by phillipskevin** [comment]
Can this be closed now @cherifGsoul ?

**Comment by cherifGsoul** [comment]
Yes, it is fixed and released!
