### ISSUE TITLE
donejs init fails during execution

### ISSUE THREAD

**Issue by mjstahl** [donejs/generator-donejs#36]
In can best be described by the following video:

https://asciinema.org/a/1wrkfvvexpfkoxeezohggdr9g

From @daffl in Slack -- For some very odd reason app/templates/.gitignore is named .npmignore in the installable generator-donejs

**Comment by mjstahl** [comment]
`npm publish` seems to ignore `.gitignore` files and replaces them with `.npmignore`. *sigh* Reference the following issue:

https://github.com/npm/npm/issues/3763

So it seems the best course of action is to rename `.gitignore` to something like `__gitignore` and replace the `__` with `.`

**Comment by daffl** [comment]
You can probably do that with a simple `name.replace('_', '.')` in https://github.com/donejs/generator-donejs/blob/master/app/index.js#L173

**Comment by mjstahl** [comment]
Close, but we have to do that at https://github.com/donejs/generator-donejs/blob/master/app/index.js#L176... otherwise we will fail to find the original file.  Pull request incoming.
