### ISSUE TITLE
Installs prereleases

### ISSUE THREAD

**Issue by matthewp** [donejs/generator-donejs#57]
donejs init is installing can-ssr prerelease and steal/steal-tools prereleases, trying to figure out why.

**Comment by matthewp** [comment]
It only does it in the test actually, not sure why.

**Comment by daffl** [comment]
Most likely because the test doesn't set `options.packages` at https://github.com/donejs/generator-donejs/blob/master/app/index.js#L145 so https://github.com/donejs/generator-donejs/blob/master/app/index.js#L155 will run instead.

**Comment by matthewp** [comment]
How are `options.package` set if you do donejs init normally?

**Comment by daffl** [comment]
This should be fixed now.
