### ISSUE TITLE
yeoman generator does not work

### ISSUE THREAD

**Issue by pYr0x** [donejs/generator-donejs#58]
as descripted in the readme:
```yo donejs:component my/component```
does not work for me.
got an error that https://github.com/donejs/generator-donejs/blob/master/component/index.js#L83 have to be a string. 
the problem is, that https://github.com/donejs/generator-donejs/blob/master/component/index.js#L70-L71 are undefined.

yeomen is installed globaly and generator-donejs isn't

which ```this.config``` will generator-donejs load?

**Comment by justinbmeyer** [comment]
Did you try `donejs component my/component some-tag`?

**Comment by daffl** [comment]
`donejs init` (or `yo donejs`) create a `.yo-rc.json` file in the root folder that stores that information. Here is how it usually looks like: https://github.com/donejs/chat/blob/master/.yo-rc.json

**Comment by pYr0x** [comment]
also throws an error 
![](http://i.snag.gy/gNLVp.jpg)

**Comment by daffl** [comment]
If `.yo-rc.json` doesn't exist the generator won't know where to put the file or what the application name is.

**Comment by pYr0x** [comment]
@daffl worked... thanks

**Comment by daffl** [comment]
I'm wondering if it should throw a better error messages. I was hoping the Yeoman would complain if you try to get a setting that doesn't exist.
