### ISSUE TITLE
Illegal module name "/my/component/component"

### ISSUE THREAD

**Issue by pYr0x** [donejs/generator-donejs#60]
creating a component with ```yo donejs:component my/component``` throw an error.

my folder structure is:

```
wecanjs / root
│
└───src
    ├───my
    └───component
        │   component.html
        │   component.js
        │   component.less
     ...
```

my ```.yo-rc.json``` looks like:
```
{
  "generator-donejs": {
    "folder": "src"
  }
}
```

my ```package.json``` have this system configuration:
```
"system": {
    "npmIgnore": [
      "devDependencies"
    ],
    "directories" : {
      "lib" : "src"
    }
  },
```

if i open the component directly like: http://localhost:8080/src/my/component/component.html
the error pops up.

the component.html is the default one, which is created with yoman.
```
<script type="text/stache" can-autorender>
  <can-import from="/my/component/" />
  <my-component></my-component>
</script>
<script src="../../../node_modules/steal/steal.js"
        main="can/view/autorender/"></script>
```

what is the problem? 
i want to open the ```component.html``` file itself.

referenced to: https://github.com/stealjs/steal/issues/543

**Comment by pYr0x** [comment]
> justinbmeyer commented 8 hours ago
```<can-import from="/my/component/" />``` should probably be ```<can-import from="wecanjs/my/component/" />```

@justinbmeyer in package.json i wrote 
```
"system": {
    "directories" : {
      "lib" : "src"
    }
```
and set the module path to ```wecanjs/my/component/```will  load the component correctly.

@matthewp 
although the System.directories.lib variable is not set to ```src```. it is not merged with the package.json config.
see the screenshot below
![image](http://i.imgur.com/y0sOnXE.png)

**Comment by pYr0x** [comment]
i found the problem!

my ```.yo-rc.json``` looks like:
```
{
  "generator-donejs": {
    "folder": "src"
  }
}
```

thats not correct! the ```name``` of the app is missed. after setting the app-name, the generator works.

the correct ```.yo-rc.json``` file looks like:
```
{
  "generator-donejs": {
    "folder": "src",
    "name": "wecanjs"
  }
}
``

**Comment by matthewp** [comment]
The `.yo-rc.json` is generated when you do a donejs init. The user should never have to touch it.

**Comment by pYr0x** [comment]
@matthewp i agree, but with the project i am working on - using vagrant on windows - we found out, that we cant use symlinks. so i have to do some workarounds. first of all, set up a donejs app without using the donejs repo (no donejs cli). i have to use the donejs generator from the scratch.

i am writing a little code thats loading the package.json file if it is specified in the ```.yo-rc.json```

you can look over it and correct something if you like

**Comment by pYr0x** [comment]
@daffl should we remove https://github.com/donejs/generator-donejs/blob/master/app/index.js#L109-L110
and add 
```
this.config.set('configMain', ''package.json);
```
?

**Comment by daffl** [comment]
I'm not sure what that does there. Are you saying that we should always read this information from our `package.json` and not store it in `.yo-rc.json`?

**Comment by pYr0x** [comment]
yes.
so we have one configuration and not two on different places

**Comment by matthewp** [comment]
What configuration is needed. I worry a little but about putting too much into package.json. What would that look like?

**Comment by pYr0x** [comment]
@matthewp the information is still there...

appName => package.json => name
folder => package.json => system.directories.lib

**Comment by matthewp** [comment]
Ok, I was confused, we aren't adding new stuff into the package.json that is currently in .yo-rc.json?

**Comment by pYr0x** [comment]
no the `.yo-rc.json` have that content
```
{
  "generator-donejs": {
    "folder": "src",
    "name": "wecanjs"
  }
}
```
so we can rewrite that file to:
```
{
  "generator-donejs": {
    "configMain": "package.json"
  }
}
```

**Comment by matthewp** [comment]
and so were would the stuff currently in .yo-rc.json go?

**Comment by daffl** [comment]
It's not necessary. @pYr0x is right, all that information already is contained in the `package.json`.

**Comment by pYr0x** [comment]
i can make a PR which is working
