### ISSUE TITLE
SuperModel generator doesn't remove -'s from names

### ISSUE THREAD

**Issue by julia-allyce** [donejs/generator-donejs#65]
If you create a supermodel like so:
`donejs add supermodel my-new-model`

It will generate model files with out removing the "-" from variable names

like this:
```
export const My-New-Model = can.Map.extend({
  define: {}
});
```

This makes javascript sad :[

**Comment by daffl** [comment]
Hm, I thought `_.kebabCase` does that. I'll double check.

**Comment by daffl** [comment]
Oh... it has to be `_.camelCase` indeed.
