### ISSUE TITLE
donejs add not working without system.directories.lib

### ISSUE THREAD

**Issue by James0x57** [donejs/generator-donejs#72]
Cannot generate components for projects not using system.directories.lib
It throws this error:
The 'name' or 'system.directories.lib' is not specified in your package.json file.

**Comment by pYr0x** [comment]
@James0x57 you need the property system.directories.lib in your package.json

**Comment by justinbmeyer** [comment]
@pYr0x It shouldn't.  If there is no `directories.lib` it should assume things go in the same folder as package.json.

**Comment by pYr0x** [comment]
for consistency i would prefer to have a `directories.lib`in the package.json. it can be empty if not needed ... 
but if we make `directories.lib` optional people can thinking to remove that from package.json but thats not donejs app looks like (http://donejs.com/place-my-order.html#section=section_Createtheproject)
