### ISSUE TITLE
Error when trying to start a new plugin.

### ISSUE THREAD

**Issue by marshallswain** [donejs/generator-donejs#75]
I got the error `Error: No DoneJS dependency package list provided!` when trying to generate a fresh plugin.  Maybe I'm using this incorrectly?  Do I have to generate a plugin from within an existing DoneJS project?

```console
Bitovis-MacBook-Pro:Sites Bitovi$ yo donejs:plugin geo-location
? Project name geo-location
? Project main folder src
? Description A CanJS component that produces live-bindable geolocation data.
? Project homepage url https://github.com/icanjs/geo-location
? GitHub username or organization icanjs
? Author's Name Marshall Thompson
? Author's Email marshall@creativeideal.net
? Author's Homepage https://github.com/icanjs
? Application keywords canjs,can,component,geolocation
? NPM version used 2
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: No DoneJS dependency package list provided!
    at module.exports.generators.Base.extend.writing (/Users/Bitovi/.npm-packages/lib/node_modules/generator-donejs/plugin/index.js:145:13)
    at /Users/Bitovi/.npm-packages/lib/node_modules/generator-donejs/node_modules/yeoman-generator/lib/base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
Bitovis-MacBook-Pro:Sites Bitovi$ 
```

**Comment by daffl** [comment]
This one and the app generator can only be used through the DoneJS cli (`donejs plugin`) because it has to use the dependencies defined in your local DoneJS installation.

**Comment by marshallswain** [comment]
Is there another one somewhere else?  Or am I jumping the gun?

**Comment by daffl** [comment]
Can't you just use `donejs plugin geo-location` instead of `yo` directly?

**Comment by marshallswain** [comment]
I was just following the README.md.

**Comment by daffl** [comment]
Did it talk about `plugin`? I think we have to at least change it to say that `app` and `plugin` will not work outside of the DoneJS CLI though.

**Comment by marshallswain** [comment]
Fair enough.  It doesn't actually talk about `plugin`. I was inferring usage from the rest of the [README.md](https://github.com/donejs/generator-donejs/blob/master/readme.md).

**Comment by matthewp** [comment]
The readme should probably be updated here, I don't think we ever intended you to use `yo` directly, we're just using yeoman as an implementation detail. Could swap it out for something else in the future.

We do need this documentation some where though.

**Comment by marshallswain** [comment]
Why don't I just replace the ones in the README.md with their `donejs` counterparts?

**Comment by marshallswain** [comment]
Actually, maybe it's better to put a note at the beginning of the README that links to the donejs-cli repo and I can document them in the [README there](https://github.com/donejs/cli)

**Comment by matthewp** [comment]
I think that makes sense.
