### ISSUE TITLE
donejs develop for plugins

### ISSUE THREAD

**Issue by daffl** [donejs/generator-donejs#82]
It should start a static file server and `steal-tools live-reload`

**Comment by daffl** [comment]
Closed via https://github.com/canjs/can-ssr/pull/135

**Comment by daffl** [comment]
I added static file hosting to `can-ssr` but I don't know how live-reload is supposed to work. Running `steal-tools live-reload` shows that files are being reloaded but nothing happens which is probably to be expected since neither the demo page or the tests offer a `reload` functionality.

@matthewp any insights?

**Comment by matthewp** [comment]
Is `live-reload` in the package.json configDependencies?  If so demo pages should be working. Only thing I can think is on demo pages if you are doing:

```html
<script src="path/to/steal.js">
  import 'stuff'
</script>
```

maybe not handling that parent correctly.

**Comment by daffl** [comment]
Indeed, it wasn't added to configDependencies. The tests now reload automatically (kind of, the QUnit status doesn't change from red to green when live-reloading) but component demo pages still do not reload.

**Comment by daffl** [comment]
This has been done in the latest version
